### ISSUE TITLE
Missing Colon In Latest Commit

### ISSUE THREAD

**Issue by paulanthonymeier** [mattpfeffer/tailwind-fontawesome#6]
There's a colon missing in your latest commit in ./src/index.js

 Line 28 Col 100 ...
'.icon-before::before, .icon-after::after, .icon-outside::before, .icon-inline' {

Should be ...
'.icon-before::before, .icon-after::after, .icon-outside::before, .icon-inline': {

**Comment by mattpfeffer** [comment]
@paulanthonymeier Yikes, good catch. Patch rolled out via 0.7.1.
